config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :movies
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, presence: true
  validates :list, presence: true
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, :overview, presence: true
  validates :title, uniqueness: true
  validates :overview, uniqueness: true

  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]
  before_action :set_bookmark, only: [:destroy]

  def new
    @bookmark = @list.bookmarks.build
    @movies = Movie.all
  end

  def create
    @bookmark = @list.bookmarks.build(bookmark_params)
    if @bookmark.save
      redirect_to @list, notice: 'Bookmark was successfully created.'
    else
      @movies = Movie.all
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to @bookmark.list, notice: 'Bookmark was successfully destroyed.'
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to @list, notice: 'List was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_url, notice: 'List was successfully destroyed.'
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie, notice: "Movie was successfully created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @movie.update(movie_params)
      redirect_to @movie, notice: 'Movie was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    if @movie.bookmarks.any?
      redirect_to @movie, alert: 'Cannot delete movie with associated bookmarks.'
    else
      @movie.destroy
      redirect_to movies_url, notice: 'Movie was successfully destroyed.'
    end
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :overview, :poster_url, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>Add a New Bookmark</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.button :submit, 'Create Bookmark' %>
<% end %>

<%= link_to 'Back to List', list_path(@list) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<h1>These are your lists:</h1>

<ul>
  <% @lists.each do |list| %>
    <li><%= list.name %></li>
        <p>
          <%= link_to "Show this list", list %>
        </p>
  <% end %>
</ul>

<%= link_to "Create a new list", new_list_path %>

app/views/lists/new.html.erb
<h2>Add a New List</h2>

<%= render "form", list: @list %>

<%= link_to "Back to all lists", lists_path %>

app/views/lists/show.html.erb
<h1>This is your list of interest:</h1>

<h2><%= @list.name %></h2>

<h3>Comments:</h3>
<ul>
  <% @list.bookmarks.each do |bookmark| %>
    <li><%= bookmark.movie.title %></li>
      <%= bookmark.comment %><br>
      <%= link_to "Remove Comment", bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure you want to delete this bookmark?" } %>
  <% end %>
</ul>

<%= link_to "Back to all movies", movies_path %>

<%= link_to "Back to your lists", lists_path %>

<%= link_to "Create a new bookmark for this list", new_list_bookmark_path(@list) %>

app/views/movies/index.html.erb
<h1>These are your movies:</h1>

<ul>
  <% @movies.each do |movie| %>
    <li><%= movie.title %><%= movie.rating %></li>
    <p><%= movie.overview %></p>
  <% end %>
</ul>

app/views/movies/show.html.erb
<h1>This is your movie of interest:</h1>

<h2><%= @movie.title %></h2>
<p><%= @movie.overview %></p>
<p><%= @movie.rating %></p>
<p><%= @movie.url %></p>

<%= link_to "Back to all movies", movies_path %>

<%= link_to "Back to your lists", lists_path %>